apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_img
        imagePullPolicy: Never
        ports:
          - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
   metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: wordpress
  ports:
  - name: wordpress
    protocol: TCP
    port: 5050
  type: LoadBalancer
  loadBalancerIP: 192.168.99.188